question_data = [
     {"category": "General Knowledge",
     "type": "boolean", "difficulty": "easy",
     "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "Bulls are attracted to the color red.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "The Sun rises from the North.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "The color orange is named after the fruit.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
      "incorrect_answers": ["True"]}
]
